### ISSUE TITLE
.NET demo has missing dependency

### ISSUE THREAD

**Issue by lionelhorn** [Picovoice/rhino#47]
Hello, 

I tried to run your .NET demo on Win10 v1909 FR.

`dotnet run -c MicDemo.Release -- --context_path "C:\Users\Username\Desktop\model.rhn"`

It crashes with

```cmd
Listening
System.DllNotFoundException: Could not load the dll 'openal32.dll' (this load is intercepted, specified in DllImport as 'AL').
   at OpenTK.Audio.OpenAL.ALLoader.ImportResolver(String libraryName, Assembly assembly, Nullable1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at OpenTK.Audio.OpenAL.ALC.CaptureOpenDevice(String devicename, Int32 frequency, ALFormat format, Int32 buffersize)
   at RhinoDemo.MicDemo.RunDemo(String contextPath, String modelPath, Single sensitivity, Nullable1 audioDeviceIndex, String outputPath) in  E:\rhino\demo\dotnet\RhinoDemo\MicDemo.cs:line 83
   at RhinoDemo.MicDemo.Main(String[] args) in E:\rhino\demo\dotnet\RhinoDemo\MicDemo.cs:line 296
``` 

Seems related to https://github.com/opentk/opentk/issues/1169

**Comment by kenarsa** [comment]
Have you installed  OpenAL?

https://github.com/Picovoice/rhino/tree/master/demo/dotnet#installation

**Comment by kenarsa** [comment]
@lionelhorn, any updates?
